# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anansiwebcalc.ui'
#
# Created: Mon Oct 10 17:21:16 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AnansiWebCalc(object):
    def setupUi(self, AnansiWebCalc):
        AnansiWebCalc.setObjectName(_fromUtf8("AnansiWebCalc"))
        AnansiWebCalc.resize(434, 302)
        AnansiWebCalc.setWindowTitle(QtGui.QApplication.translate("AnansiWebCalc", "AnansiWebCalc", None, QtGui.QApplication.UnicodeUTF8))
        self.centralWidget = QtGui.QWidget(AnansiWebCalc)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.btn1 = QtGui.QPushButton(self.centralWidget)
        self.btn1.setGeometry(QtCore.QRect(10, 190, 41, 31))
        self.btn1.setText(QtGui.QApplication.translate("AnansiWebCalc", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.btn1.setObjectName(_fromUtf8("btn1"))
        self.btn2 = QtGui.QPushButton(self.centralWidget)
        self.btn2.setGeometry(QtCore.QRect(60, 190, 41, 31))
        self.btn2.setText(QtGui.QApplication.translate("AnansiWebCalc", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.btn2.setObjectName(_fromUtf8("btn2"))
        self.btn3 = QtGui.QPushButton(self.centralWidget)
        self.btn3.setGeometry(QtCore.QRect(110, 190, 41, 31))
        self.btn3.setText(QtGui.QApplication.translate("AnansiWebCalc", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.btn3.setObjectName(_fromUtf8("btn3"))
        self.btn4 = QtGui.QPushButton(self.centralWidget)
        self.btn4.setGeometry(QtCore.QRect(10, 150, 41, 31))
        self.btn4.setText(QtGui.QApplication.translate("AnansiWebCalc", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.btn4.setObjectName(_fromUtf8("btn4"))
        self.btn5 = QtGui.QPushButton(self.centralWidget)
        self.btn5.setGeometry(QtCore.QRect(60, 150, 41, 31))
        self.btn5.setText(QtGui.QApplication.translate("AnansiWebCalc", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.btn5.setObjectName(_fromUtf8("btn5"))
        self.btn6 = QtGui.QPushButton(self.centralWidget)
        self.btn6.setGeometry(QtCore.QRect(110, 150, 41, 31))
        self.btn6.setText(QtGui.QApplication.translate("AnansiWebCalc", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.btn6.setObjectName(_fromUtf8("btn6"))
        self.btn7 = QtGui.QPushButton(self.centralWidget)
        self.btn7.setGeometry(QtCore.QRect(10, 110, 41, 31))
        self.btn7.setText(QtGui.QApplication.translate("AnansiWebCalc", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.btn7.setObjectName(_fromUtf8("btn7"))
        self.btn8 = QtGui.QPushButton(self.centralWidget)
        self.btn8.setGeometry(QtCore.QRect(60, 110, 41, 31))
        self.btn8.setText(QtGui.QApplication.translate("AnansiWebCalc", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.btn8.setObjectName(_fromUtf8("btn8"))
        self.btn9 = QtGui.QPushButton(self.centralWidget)
        self.btn9.setGeometry(QtCore.QRect(110, 110, 41, 31))
        self.btn9.setText(QtGui.QApplication.translate("AnansiWebCalc", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.btn9.setObjectName(_fromUtf8("btn9"))
        self.btnBack = QtGui.QPushButton(self.centralWidget)
        self.btnBack.setGeometry(QtCore.QRect(10, 70, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setText(QtGui.QApplication.translate("AnansiWebCalc", "←", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBack.setObjectName(_fromUtf8("btnBack"))
        self.btnClearAll = QtGui.QPushButton(self.centralWidget)
        self.btnClearAll.setGeometry(QtCore.QRect(60, 70, 41, 31))
        self.btnClearAll.setText(QtGui.QApplication.translate("AnansiWebCalc", "CE", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearAll.setObjectName(_fromUtf8("btnClearAll"))
        self.btnClearCur = QtGui.QPushButton(self.centralWidget)
        self.btnClearCur.setGeometry(QtCore.QRect(110, 70, 41, 31))
        self.btnClearCur.setText(QtGui.QApplication.translate("AnansiWebCalc", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearCur.setObjectName(_fromUtf8("btnClearCur"))
        self.equalsBtn = QtGui.QPushButton(self.centralWidget)
        self.equalsBtn.setGeometry(QtCore.QRect(210, 190, 41, 71))
        self.equalsBtn.setText(QtGui.QApplication.translate("AnansiWebCalc", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.equalsBtn.setObjectName(_fromUtf8("equalsBtn"))
        self.btn0 = QtGui.QPushButton(self.centralWidget)
        self.btn0.setGeometry(QtCore.QRect(10, 230, 91, 31))
        self.btn0.setText(QtGui.QApplication.translate("AnansiWebCalc", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.btn0.setObjectName(_fromUtf8("btn0"))
        self.btnDecimal = QtGui.QPushButton(self.centralWidget)
        self.btnDecimal.setGeometry(QtCore.QRect(110, 230, 41, 31))
        self.btnDecimal.setText(QtGui.QApplication.translate("AnansiWebCalc", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDecimal.setObjectName(_fromUtf8("btnDecimal"))
        self.btnAdd = QtGui.QPushButton(self.centralWidget)
        self.btnAdd.setGeometry(QtCore.QRect(160, 230, 41, 31))
        self.btnAdd.setText(QtGui.QApplication.translate("AnansiWebCalc", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.btnMinus = QtGui.QPushButton(self.centralWidget)
        self.btnMinus.setGeometry(QtCore.QRect(160, 190, 41, 31))
        self.btnMinus.setText(QtGui.QApplication.translate("AnansiWebCalc", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMinus.setObjectName(_fromUtf8("btnMinus"))
        self.btnMult = QtGui.QPushButton(self.centralWidget)
        self.btnMult.setGeometry(QtCore.QRect(160, 150, 41, 31))
        self.btnMult.setText(QtGui.QApplication.translate("AnansiWebCalc", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMult.setObjectName(_fromUtf8("btnMult"))
        self.btnDiv = QtGui.QPushButton(self.centralWidget)
        self.btnDiv.setGeometry(QtCore.QRect(160, 110, 41, 31))
        self.btnDiv.setText(QtGui.QApplication.translate("AnansiWebCalc", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDiv.setObjectName(_fromUtf8("btnDiv"))
        self.btnPosNegative = QtGui.QPushButton(self.centralWidget)
        self.btnPosNegative.setGeometry(QtCore.QRect(160, 70, 41, 31))
        self.btnPosNegative.setText(QtGui.QApplication.translate("AnansiWebCalc", "±", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPosNegative.setObjectName(_fromUtf8("btnPosNegative"))
        self.listView = QtGui.QListView(self.centralWidget)
        self.listView.setGeometry(QtCore.QRect(255, 10, 171, 251))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.btnXSq = QtGui.QPushButton(self.centralWidget)
        self.btnXSq.setGeometry(QtCore.QRect(210, 150, 41, 31))
        self.btnXSq.setText(QtGui.QApplication.translate("AnansiWebCalc", "x²", None, QtGui.QApplication.UnicodeUTF8))
        self.btnXSq.setObjectName(_fromUtf8("btnXSq"))
        self.btnPi = QtGui.QPushButton(self.centralWidget)
        self.btnPi.setGeometry(QtCore.QRect(210, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnPi.setFont(font)
        self.btnPi.setText(QtGui.QApplication.translate("AnansiWebCalc", "pi", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPi.setObjectName(_fromUtf8("btnPi"))
        self.btnParents = QtGui.QPushButton(self.centralWidget)
        self.btnParents.setGeometry(QtCore.QRect(210, 70, 41, 31))
        self.btnParents.setText(QtGui.QApplication.translate("AnansiWebCalc", "(  )", None, QtGui.QApplication.UnicodeUTF8))
        self.btnParents.setObjectName(_fromUtf8("btnParents"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralWidget)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 12, 241, 51))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        AnansiWebCalc.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(AnansiWebCalc)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setTitle(QtGui.QApplication.translate("AnansiWebCalc", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("AnansiWebCalc", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        AnansiWebCalc.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(AnansiWebCalc)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        AnansiWebCalc.setStatusBar(self.statusBar)
        self.actionHelp = QtGui.QAction(AnansiWebCalc)
        self.actionHelp.setText(QtGui.QApplication.translate("AnansiWebCalc", "Help...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(AnansiWebCalc)
        self.actionAbout.setText(QtGui.QApplication.translate("AnansiWebCalc", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionClear_All = QtGui.QAction(AnansiWebCalc)
        self.actionClear_All.setText(QtGui.QApplication.translate("AnansiWebCalc", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_All.setObjectName(_fromUtf8("actionClear_All"))
        self.actionExit = QtGui.QAction(AnansiWebCalc)
        self.actionExit.setText(QtGui.QApplication.translate("AnansiWebCalc", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionClear_All)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AnansiWebCalc)
        QtCore.QMetaObject.connectSlotsByName(AnansiWebCalc)

    def retranslateUi(self, AnansiWebCalc):
        pass

